stages:
  - build
  - release
  - deploy

build:
  stage: build
  only:
    - tags
  image: node:9
  artifacts:
    paths:
      - app/
      - node_modules/
      - server/
      - shared/
      - Dockerfile
  script:
    - npm install
    - npm run build:prod

release:
  stage: release
  only:
    - tags
  variables:
    GIT_STRATEGY: none
  image: gitlab/dind:latest
  dependencies:
    - build
  script:
    - docker build -t planning-poker:$CI_COMMIT_TAG .

deploy:
  stage: deploy
  only:
    - tags
  when: manual
  allow_failure: false
  variables:
    GIT_STRATEGY: none
  image: gitlab/dind:latest
  script:
    - docker stop planning-poker || true
    - docker rm planning-poker || true
    - docker run -d --name planning-poker --restart always --network bridge planning-poker:$CI_COMMIT_TAG
  